///blur(fade,alpha,c_white,false)
b=instance_create(x,y,obj_blur)
b.fade=argument0
b.sprite_index=sprite_index
b.image_alpha=argument1
b.image_xscale=image_xscale
b.image_yscale=image_yscale
b.image_angle=image_angle
b.depth=depth
b.color=argument2
b.fog=argument3
